projectName: test_horsepower1
groupId: com.test_horsepower1
artifactId: '{{ .projectName | replace "-" "_" }}'
applicationName: "{{ .projectName }}-server"
version: 1.0-SNAPSHOT
vsVersion: 1.0.0
projectId: 3fdc654b-feb2-4d4a-be19-e9ca2998b5d6
dbType: mysql
dbHost: 10.0.2.201
dbPort: 3306
package: "{{ .groupId }}.{{ .artifactId }}"
packagePath: '{{ .package | replace "." "/" }}'
dbDatabase: '{{ .projectName | replace "-" "_" }}'
dbUser: '{{ .projectName | replace "-" "_" }}_user'
dbPassword: "{{ randAlphaNum 16 }}"
rocketmq_address: "10.0.2.221:9876;10.0.2.222:9876;10.0.2.223:9876"
rocketmq_topic: '{{ .projectName | replace "-" "_" }}'
rocketmq_consumerGroup: "CID_{{ .artifactId }}"
rocketmq_producerGroup: "PID_{{ .artifactId }}"
elasticsearch_host: "10.0.2.221,10.0.2.222,10.0.2.223"
elasticsearch_port: "9200"
elasticsearch_scheme: "https"
elasticsearch_username: "admin"
elasticsearch_password: "dnZkaNVK"
xxljob_address: "https://xxljob.teitui.com/xxl-job-admin"
xxljob_username: "admin"
xxljob_password: "123456"
xxljob_accessToken: "default_token"
redis_address: "redis.byteawake.com:6379"
redis_password: ""
redis_maxTotal: 100
redis_maxIdle: 10
redis_minIdle: 10
